In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [68]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train.drop(['Test 1','Test 2' ,'Test 3','Test 4','Test 5'],axis=1,inplace=True)
train['Patient Age'].fillna(train['Patient Age'].mode()[0],inplace = True)
train["Mother's age"].fillna(train["Mother's age"].mode()[0],inplace = True)
train["Father's age"].fillna(train["Father's age"].mode()[0],inplace = True)
train['No. of previous abortion'].fillna(train['No. of previous abortion'].mode()[0],inplace = True)
train['Symptom 1'].fillna(train['Symptom 1'].mode()[0],inplace = True)
train['Symptom 2'].fillna(train['Symptom 2'].mode()[0],inplace = True)
train['Symptom 3'].fillna(train['Symptom 3'].mode()[0],inplace = True)
train['Symptom 4'].fillna(train['Symptom 4'].mode()[0],inplace = True)
train['Symptom 5'].fillna(train['Symptom 5'].mode()[0],inplace = True)
train['White Blood cell count (thousand per microliter)'].fillna(train['White Blood cell count (thousand per microliter)'].mode()[0],inplace = True)

train.drop(['Patient Id','Patient First Name' ,'Family Name',"Father's name",'Institute Name','Location of Institute'],axis=1,inplace=True)

train.dropna(axis=0, subset=['Disorder Subclass','Genetic Disorder'],inplace=True)
train['Inherited from father'].fillna(train['Inherited from father'].mode()[0],inplace = True)
train['Maternal gene'].fillna(train['Maternal gene'].mode()[0],inplace = True)
train['Respiratory Rate (breaths/min)'].fillna(train['Respiratory Rate (breaths/min)'].mode()[0],inplace = True)
train['Heart Rate (rates/min'].fillna(train['Heart Rate (rates/min'].mode()[0],inplace = True)
train['Follow-up'].fillna(train['Follow-up'].mode()[0],inplace = True)
train['Gender'].fillna(train['Gender'].mode()[0],inplace = True)
train['Place of birth'].fillna(train['Place of birth'].mode()[0],inplace = True)
train['Folic acid details (peri-conceptional)'].fillna(train['Folic acid details (peri-conceptional)'].mode()[0],inplace = True)
train['H/O serious maternal illness'].fillna(train['H/O serious maternal illness'].mode()[0],inplace = True)
train['Assisted conception IVF/ART'].fillna(train['Assisted conception IVF/ART'].mode()[0],inplace = True)
train['History of anomalies in previous pregnancies'].fillna(train['History of anomalies in previous pregnancies'].mode()[0],inplace = True)
train['Birth defects'].fillna(train['Birth defects'].mode()[0],inplace = True)
train['Blood test result'].fillna(train['Blood test result'].mode()[0],inplace = True)

train.drop(['Parental consent'],axis=1,inplace=True)
train['Birth asphyxia'] = train['Birth asphyxia'].replace(np.nan,'Not available')
train['Autopsy shows birth defect (if applicable)'] = train['Autopsy shows birth defect (if applicable)'].replace({np.nan:'Not applicable','None':'Not applicable'})
train['H/O radiation exposure (x-ray)'] = train['H/O radiation exposure (x-ray)'].replace({np.nan:'Not applicable','-':'Not applicable'})
train['H/O substance abuse'] = train['H/O substance abuse'].replace({np.nan:'Not applicable','-':'Not applicable'})

In [69]:
train.head()

Patient Age Genes in mother's side Inherited from father Maternal gene  \
0          2.0                    Yes                    No           Yes   
2          6.0                    Yes                    No            No   
3         12.0                    Yes                    No           Yes   
4         11.0                    Yes                    No           Yes   
5         14.0                    Yes                    No           Yes   

  Paternal gene  Blood cell count (mcL)  Mother's age  Father's age    Status  \
0            No                4.760603          23.0          20.0     Alive   
2            No                4.893297          41.0          22.0     Alive   
3            No                4.705280          21.0          20.0  Deceased   
4           Yes                4.720703          32.0          20.0     Alive   
5            No                5.103188          23.0          20.0  Deceased   

  Respiratory Rate (breaths/min)  ... Birth defects  \
0                 Normal (30-60)  ...      Multiple   
2                 Normal (30-60)  ...      Singular   
3                      Tachypnea  ...      Singular   
4                      Tachypnea  ...      Multiple   
5                 Normal (30-60)  ...      Multiple   

  White Blood cell count (thousand per microliter)  Blood test result  \
0                                         9.857562  slightly abnormal   
2                                         3.000000             normal   
3                                         7.919321       inconclusive   
4                                         4.098210  slightly abnormal   
5                                        10.272230             normal   

  Symptom 1 Symptom 2 Symptom 3 Symptom 4 Symptom 5  \
0       1.0       1.0       1.0       1.0       1.0   
2       0.0       1.0       1.0       1.0       1.0   
3       0.0       0.0       1.0       0.0       0.0   
4       0.0       0.0       0.0       0.0       0.0   
5       1.0       0.0       0.0       1.0       0.0   

                               Genetic Disorder  \
0   Mitochondrial genetic inheritance disorders   
2  Multifactorial genetic inheritance disorders   
3   Mitochondrial genetic inheritance disorders   
4  Multifactorial genetic inheritance disorders   
5              Single-gene inheritance diseases   

                     Disorder Subclass  
0  Leber's hereditary optic neuropathy  
2                             Diabetes  
3                       Leigh syndrome  
4                               Cancer  
5                      Cystic fibrosis  

[5 rows x 33 columns]

In [70]:
train['Genetic Disorder'].value_counts()

Mitochondrial genetic inheritance disorders     9241
Single-gene inheritance diseases                6929
Multifactorial genetic inheritance disorders    1877
Name: Genetic Disorder, dtype: int64

In [71]:
train['Disorder Subclass'].value_counts()

Leigh syndrome                         4683
Mitochondrial myopathy                 3971
Cystic fibrosis                        3145
Tay-Sachs                              2556
Diabetes                               1653
Hemochromatosis                        1228
Leber's hereditary optic neuropathy     587
Alzheimer's                             133
Cancer                                   91
Name: Disorder Subclass, dtype: int64

In [72]:
train_independent = train.drop(['Genetic Disorder','Disorder Subclass'],axis=1) 

train_independent = pd.get_dummies(train_independent,drop_first = True)

X = train_independent
y = train['Genetic Disorder']


In [73]:
X.shape , y.shape

((18047, 39), (18047,))

In [74]:
from imblearn.over_sampling import RandomOverSampler
oversample = RandomOverSampler(sampling_strategy='not majority')
X_over, y_over = oversample.fit_resample(X, y)

In [75]:
y_over.value_counts()

Mitochondrial genetic inheritance disorders     9241
Single-gene inheritance diseases                9241
Multifactorial genetic inheritance disorders    9241
Name: Genetic Disorder, dtype: int64

In [43]:
X_over.shape

(27723, 39)

##### NOw it is balanced dataset ____ after performing oversampling

In [76]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_over, y_over, test_size=0.3, random_state=5)

from sklearn.preprocessing import StandardScaler
sm = StandardScaler()
X_train_scaled = sm.fit_transform(X_train)
X_test_scaled = sm.transform(X_test)

from sklearn.linear_model import LogisticRegression
lm = LogisticRegression()
lm.fit(X_train_scaled,y_train)
y_pred = lm.predict(X_test_scaled)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

from sklearn import metrics
print(metrics.confusion_matrix(y_test,y_pred))


from sklearn.metrics import accuracy_score
print("accuracy is: " ,accuracy_score(y_test,y_pred))

                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.55      0.40      0.46      2795
Multifactorial genetic inheritance disorders       0.63      0.83      0.72      2727
            Single-gene inheritance diseases       0.44      0.43      0.43      2795

                                    accuracy                           0.55      8317
                                   macro avg       0.54      0.55      0.54      8317
                                weighted avg       0.54      0.55      0.54      8317

[[1115  437 1243]
 [ 203 2275  249]
 [ 704  900 1191]]
accuracy is:  0.5507995671516172


In [77]:
X_train_scaled

array([[-1.59956648, -1.01766047, -0.29009726, ..., -0.54777759,
        -0.53440739,  1.46884336],
       [-1.12868897, -0.15181263, -0.89347634, ...,  1.82555842,
        -0.53440739, -0.68080779],
       [-0.65781146, -1.65491816, -0.89347634, ..., -0.54777759,
        -0.53440739,  1.46884336],
       ...,
       [-0.65781146, -0.02247586, -0.89347634, ..., -0.54777759,
        -0.53440739,  1.46884336],
       [ 0.75482106,  0.66425615,  0.21271864, ...,  1.82555842,
        -0.53440739, -0.68080779],
       [ 1.22569857,  0.28341524,  1.4194768 , ..., -0.54777759,
        -0.53440739,  1.46884336]])

In [78]:
from sklearn.tree import DecisionTreeClassifier
ex_decision = DecisionTreeClassifier()
ex_decision.fit(X_train_scaled,y_train)
y_pred = ex_decision.predict(X_test_scaled)
print(ex_decision.score(X_train_scaled,y_train))
                

print(metrics.confusion_matrix(y_test,y_pred))
                        

print(metrics.accuracy_score(y_test,y_pred))
print(metrics.classification_report(y_test, y_pred))

1.0
[[1536  239 1020]
 [  26 2667   34]
 [ 767  228 1800]]
0.7217746783696044
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.66      0.55      0.60      2795
Multifactorial genetic inheritance disorders       0.85      0.98      0.91      2727
            Single-gene inheritance diseases       0.63      0.64      0.64      2795

                                    accuracy                           0.72      8317
                                   macro avg       0.71      0.72      0.72      8317
                                weighted avg       0.71      0.72      0.71      8317



In [82]:
from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier()
model2.fit(X_train_scaled, y_train)
y_pred2 = model2.predict(X_test_scaled)
print(model2.score(X_train_scaled,y_train))
                

print(metrics.confusion_matrix(y_test,y_pred2))
                        

print(metrics.accuracy_score(y_test,y_pred2))
print(metrics.classification_report(y_test, y_pred2))

1.0
[[2089  164  542]
 [  18 2690   19]
 [ 940  213 1642]]
0.7720331850426837
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.69      0.75      0.72      2795
Multifactorial genetic inheritance disorders       0.88      0.99      0.93      2727
            Single-gene inheritance diseases       0.75      0.59      0.66      2795

                                    accuracy                           0.77      8317
                                   macro avg       0.77      0.77      0.77      8317
                                weighted avg       0.77      0.77      0.77      8317



In [81]:
import xgboost as xgb
model5 = xgb.XGBClassifier()
model5.fit(X_train_scaled, y_train)
y_pred5 = model5.predict(X_test_scaled)
print(model5.score(X_train_scaled,y_train))
print(metrics.confusion_matrix(y_test,y_pred5))
print(metrics.accuracy_score(y_test,y_pred5))
print(metrics.classification_report(y_test, y_pred5))

0.913480366896836
[[1717  238  840]
 [  60 2614   53]
 [ 832  365 1598]]
0.7128772393892029
                                              precision    recall  f1-score   support

 Mitochondrial genetic inheritance disorders       0.66      0.61      0.64      2795
Multifactorial genetic inheritance disorders       0.81      0.96      0.88      2727
            Single-gene inheritance diseases       0.64      0.57      0.60      2795

                                    accuracy                           0.71      8317
                                   macro avg       0.70      0.71      0.71      8317
                                weighted avg       0.70      0.71      0.71      8317



################ Hyper parameter tuning #######################

In [83]:
from sklearn.model_selection import RandomizedSearchCV
RF = RandomForestClassifier()
paramgrid = { 'n_estimators': [50,80,100,120,140,150,180,200],
    'criterion':['gini','entropy'],
    'max_depth':[3,5,8,10]}
random = RandomizedSearchCV(RF, paramgrid, random_state=0 )
RF_clf = random.fit(X_train_scaled,y_train)

KeyboardInterrupt: 

In [ ]:
print(RF_clf.best_estimator_)